### ISSUE TITLE
Gem raises exception on requests

### ISSUE THREAD

**Issue by rrunyon** [scoutapp/ruby_server_timing#1]
`ServerTiming raised an exception: uninitialized constant ServerTiming::ResponseManipulator::ScoutApm`

**Comment by itsderek23** [comment]
@rrunyon - sorry and thanks for reporting!

Can you verify that `scout_apm` is in your `Gemfile.lock` file?

**Comment by abraham** [comment]
I'm seeing the same thing.

`Gemfile.lock` includes:
```
    scout_apm (2.4.8)
    server_timing (1.0.0)
      scout_apm
```

If I explicitly add `scout_apm` to `Gemfile` it works.

**Comment by itsderek23** [comment]
Mind:

* removing the explicit require of `scout_apm` in your `Gemfile`
* `bundle update server_timing` (v1.0.1)

#3 should address this issue.

**Comment by abraham** [comment]
Works for me. 👍

**Comment by itsderek23** [comment]
Great!

`server_timing` v1.0.1 should fix this issue. 

If you are on v1.0.0, run `bundle update server_update` to grab the latest.
