### ISSUE TITLE
Incorrect Server-Timing syntax?

### ISSUE THREAD

**Issue by PikachuEXE** [scoutapp/ruby_server_timing#5]
## Env
**Server**
`ruby_server_timing` `1.0.1`

**Browser**
Chrome: Version 64.0.3282.186 (Official Build) (64-bit)

## Actual Output
```
server-timing:Middleware; dur=82.11; ,Router; dur=881.89; ,Controller; dur=152.58; ,ActiveRecord; dur=69.31; ,Redis; dur=356.72; ,View; dur=14509.94; ,Total; dur=16052.57;
```
![screen shot 2018-03-05 at 3 46 37 pm](https://user-images.githubusercontent.com/1018543/36962937-682b4b30-208c-11e8-855c-4ca77c898f96.png)

If I use https://github.com/dpogue/rails_server_timings
It outputs as 
```
server-timing:view=0.794, db=0.882, redis=0.447, total=36.107
```
![screen shot 2018-03-05 at 3 48 25 pm](https://user-images.githubusercontent.com/1018543/36963028-a99805b8-208c-11e8-99b1-d5706fb67491.png)

**Comment by cvazac** [comment]
Chrome 64 expects the old format:
```
Server-Timing: metric=123.4;the_description
```

Chrome 65+ (and other browsers when they implement the feature) expects the new format:
```
Server-Timing: metric;dur=123.4;desc=the_description
```

**Comment by itsderek23** [comment]
Thanks @PikachuEXE for reporting and @cvazac for the background. 

I'd prefer to keep it simple and stay consistent w/Chrome 65+ and future browser implementations. I've added a note to the README for others than run into an issue with Chrome 64:

https://github.com/scoutapp/ruby_server_timing/commit/9a10c2e4c9b663645dba9e1486802645fda3ccf9

**Comment by PikachuEXE** [comment]
Thanks
Do you know what version of Chromium are supporting the new format?
Since I use Vivaldi (based on Chromium) most of the time

**Comment by itsderek23** [comment]
I believe Chrome 65+.

**Comment by itsderek23** [comment]
Ah sorry @PikachuEXE - responded to fast. I'm not sure what version of Chromium (vs Chrome) uses the new format.
