### ISSUE TITLE
Permissions of log file in production are incorrect?

### ISSUE THREAD

**Issue by ostigley** [scoutapp/ruby_server_timing#8]
Hi there,
firstly, I like this gem, thanks for the contribution!

When deploying this to staging or production, I've found that the scout_api.log file is created with the incorrect file ownership and permissions.  This resulted in the app not booting successfully. 

I'm not sure if this is a problem with our custom production set up (various users and groups), or a problem with the gem.   Just thought I'd let you know. 

We are running thin servers, and the scout_api.log file needed to have the same permissions as the thin logs, which it did not.  This may well be due to our custom deploy process, but we have not encountered it before. 

Cheers

**Comment by itsderek23** [comment]
@ostigley - thanks for reporting this. 

I don't recall hearing this issue reported yet inside the [scout_apm_ruby](https://github.com/scoutapp/scout_apm_ruby) repo. It smells like a user-switching issue ... for example, the log file was created under the root user, but then the process owner switched to another user.

One option: change the [log file path](http://help.apm.scoutapp.com/#log_file_path) to `STDOUT` in the `scout_apm.yml` file:

```yaml
common: &defaults
  monitor: true
  log_file_path: STDOUT

production:
  <<: *defaults
```
